"""Convenience exports for portfolio, risk, curve construction, and curve fitting."""

from .curve_fitting import (
    NelsonSiegelFitResult,
    SvenssonFitResult,
    curve_fit_comparison_data,
    curve_fit_metrics,
    fit_nelson_siegel,
    fit_svensson,
    generate_nelson_siegel_curve,
    generate_svensson_curve,
    nelson_siegel_rate,
    svensson_rate,
)
from .market_data import (
    FRED_TREASURY_SERIES_TO_TENOR,
    fetch_fred_treasury_curve,
    generate_sample_market_data,
    historical_curves_for_var,
    latest_curve_change_from_market_data,
    latest_curve_from_market_data,
    load_market_data_from_csv,
    save_market_data_to_csv,
    tenor_time_series_from_market_data,
    yield_curve_from_market_data,
)
from .curve_pricing import key_rate_risk
from .yield_curve import (
    bootstrap_from_deposits,
    bootstrap_from_deposits_and_swaps,
    curve_summary,
    forward_rate,
)
from .portfolio import (
    bond_analytics_table,
    portfolio_key_rate_risk_table,
    portfolio_key_rate_summary,
    portfolio_summary,
)
from .risk import (
    calculate_historical_curve_shocks,
    convexity,
    dv01,
    expected_shortfall,
    generate_sample_historical_yield_curves,
    historical_var,
    macaulay_duration,
    modified_duration,
    parametric_var,
    parametric_var_from_pnl,
    portfolio_risk_summary,
    run_stress_tests,
    simulate_portfolio_pnl_from_curve_shocks,
)

__all__ = [
    "bond_analytics_table",
    "bootstrap_from_deposits",
    "bootstrap_from_deposits_and_swaps",
    "curve_summary",
    "forward_rate",
    "FRED_TREASURY_SERIES_TO_TENOR",
    "fetch_fred_treasury_curve",
    "latest_curve_from_market_data",
    "yield_curve_from_market_data",
    "historical_curves_for_var",
    "latest_curve_change_from_market_data",
    "tenor_time_series_from_market_data",
    "save_market_data_to_csv",
    "load_market_data_from_csv",
    "generate_sample_market_data",
    "nelson_siegel_rate",
    "svensson_rate",
    "fit_nelson_siegel",
    "fit_svensson",
    "generate_nelson_siegel_curve",
    "generate_svensson_curve",
    "curve_fit_comparison_data",
    "curve_fit_metrics",
    "NelsonSiegelFitResult",
    "SvenssonFitResult",
    "key_rate_risk",
    "portfolio_summary",
    "portfolio_key_rate_risk_table",
    "portfolio_key_rate_summary",
    "macaulay_duration",
    "modified_duration",
    "dv01",
    "convexity",
    "calculate_historical_curve_shocks",
    "simulate_portfolio_pnl_from_curve_shocks",
    "historical_var",
    "expected_shortfall",
    "parametric_var",
    "parametric_var_from_pnl",
    "run_stress_tests",
    "portfolio_risk_summary",
    "generate_sample_historical_yield_curves",
]
